services:
  db:
    container_name: nti-pg
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nti
    ports:
      - "5432:5432"
    volumes:
      - nti:/var/lib/postgresql/data

  backend:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NODE_ENV=production

volumes:
  nti:


